version: '3'
services:
  grafana:
    build: ./docker/
    container_name: grafana
    environment:
      TZ: Europe/London
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/influxdb:/var/lib/influxdb
    ports:
      - 3003:3003
      - 8086:8086
      - 5144:514/udp
